Issue 193 related policies
Call-for-Code-for-Racial-Justice/Truth-Loop pull request #253
Opened 2021-11-08 14:03 UTC by felizj17

Contributes to #193 

## What did you do?
Added the related policies to the details accordion. Created a RelatedPolicyDetails component and test for it.  Also imported the filtermenu.scss file to the FilterMenu.js file 
## Why did you do it?
it was needed.
## How have you tested it?
Wrote test for it and viewed the page
## Were docs updated if needed?

- [ ] No
- [ ] Yes
- [x] N/A

#### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new console logs
- [ ] Fixes entire issue
- [x] Partial fix for issue

2021-11-13 00:05 UTC, markstur requested changes
There is a string/number mismatch that should be fixed.  Some other minor things (see inline comments) that you should fix while fixing that one problem.

2021-11-13 00:05 UTC, markstur commented on client/src/policyDetail/DetailsAccordion.js
> +              id={relatedPolicy.id}
I think the fix is to change the prop type to number (see below)

2021-11-13 00:05 UTC, markstur commented on client/src/policyDetail/RelatedPolicyDetails.js
> +  id: PropTypes.string,
id: PropTypes.number. will fix the string/number problem (see other comment).
Not sure if the fix should be here or above, but I think here.

2021-11-14 18:14 UTC, felizj17 commented
I'll take care of it today, been a little busy

2021-11-14 23:26 UTC, ed-snodgrass approved these changes
Looks good to me. All comments were addressed. Tests all pass, no linting issues. And it works :)

2021-11-15 15:48 UTC, markstur approved these changes
Thanks!

2021-11-15 15:48 UTC, merged