refactor(client): replace text with internationalizing formatter calls. close #242
Call-for-Code-for-Racial-Justice/Truth-Loop pull request #262
Opened 2022-02-17 22:39 UTC by Fiewor

Contributes to #242 

## What did you do?
Replace plain text with internationalizing formatter calls to expedite translation

## Why did you do it?
To enable users to view text in their preferred (available) language

## How have you tested it?
No

## Were docs updated if needed?
- [x] No
- [ ] Yes
- [ ] N/A

#### Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new console logs
- [x] Fixes entire issue
- [ ] Partial fix for issue

2022-02-20 19:22 UTC, ed-snodgrass commented
Hey @Fiewor , just a heads up that it failed to build this because you've checked in code using CR line endings instead of LF. 

Depending on what IDE you use there ought to be information that you can search for to show you how to adjust that.

2022-02-20 19:27 UTC, ed-snodgrass commented
It looks like RecordRoute and PolicyRoute has some strings that could be updated. I think your change was correct so once the line endings are fixed it should be a quick approval/merge. 

Thanks @Fiewor !

2022-02-22 09:14 UTC, Fiewor commented
> Hey @Fiewor , just a heads up that it failed to build this because you've checked in code using CR line endings instead of LF.
> 
> Depending on what IDE you use there ought to be information that you can search for to show you how to adjust that.

Oh. I'm just seeing that I missed this @ed-snodgrass . I'm using Visual Studio Code and yes the line ending is CRLF. I'll fix that before pushing.

2022-02-22 12:53 UTC, Fiewor commented
So, somehow, running `git status` shows that these files have been modified. 
Apart from my changes, all I did was run `npm run lint:fix`
I don't think I should be pushing all these with these PR, but could it be the reason the build is failing? @ed-snodgrass 

![image](https://user-images.githubusercontent.com/30049719/155135736-6c894ae4-6fea-448d-9e52-249f1d178818.png)

2022-03-08 02:15 UTC, ed-snodgrass requested changes
@Fiewor Thank you for this. Exactly what was needed. 

I made one comment where "Blur" is used and there is another spot around line 41 in PolicyTable.

I'm approving the changes in case

Thanks again.

2022-03-08 09:11 UTC, Fiewor commented on client/src/policyRoute/PolicyRoute.js
>  export default PolicyRoute
Thank you Ed. I'll make the changes and push

2022-03-08 09:41 UTC, Fiewor commented
Hi @ed-snodgrass .Thanks for all the help. 
I just read the docs for react-intl and I saw that there's a <FormattedMessage /> and <FormattedNumber /> that I think would be helpful and also a 'description' attribute which should help accessibility too.
What do you think? Should I try applying these? Or you'll make it a seperate issue?

2022-03-11 21:55 UTC, ed-snodgrass commented on client/src/policyRoute/PolicyRoute.js
> +PolicyRoute.propTypes = {
you're missing the import for PropTypes

2022-03-11 22:02 UTC, ed-snodgrass commented
> Hi @ed-snodgrass .Thanks for all the help. I just read the docs for _react-intl_ and I saw that there's a `<FormattedMessage />` and `<FormattedNumber />` that I think would be helpful and also a `description` attribute which should help accessibility too. What do you think? Should I try applying these? Or maybe you could make it a separate issue?

It is probably worth looking into but as a separate issue. Once this PR is merged you might want to play around with `<FormattedMessage />` and `<FormattedNumber />` and see if you think it is something we should look into.

Thanks again.

2022-03-11 22:05 UTC, Fiewor commented on client/src/policyRoute/PolicyRoute.js
> +PolicyRoute.propTypes = {
My bad. I'll resolve this

2022-03-11 22:06 UTC, Fiewor commented
> > Hi @ed-snodgrass .Thanks for all the help. I just read the docs for _react-intl_ and I saw that there's a `<FormattedMessage />` and `<FormattedNumber />` that I think would be helpful and also a `description` attribute which should help accessibility too. What do you think? Should I try applying these? Or maybe you could make it a separate issue?
> 
> It is probably worth looking into but as a separate issue. Once this PR is merged you might want to play around with `<FormattedMessage />` and `<FormattedNumber />` and see if you think it is something we should look into.
> 
> Thanks again.

Alright!

2022-04-03 23:09 UTC, Fiewor commented on client/src/policyRoute/PolicyRoute.js
>  const PolicyRoute = () => {
Thank you @ed-snodgrass 
Apologies for not completing this at once and having to correct errors multiple times

2022-04-22 21:40 UTC, ed-snodgrass approved these changes
Thanks again @Fiewor . 

This fixes #242

2022-04-22 21:40 UTC, merged